### ISSUE TITLE
403 Forbidden - Access Denied Error

### ISSUE THREAD

**Issue by JooRichard** [microsoftgraph/msgraph-sdk-php#1094]
Hello,

I am trying to read inbox messages but getting the below error:
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://graph.microsoft.com/v1.0/me/messages` resulted in a `403 Forbidden` response:
{"error":{"code":"ErrorAccessDenied","message":"Access is denied. Check credentials and try again."}}
 in E:\xampp\htdocs\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
Stack trace:
#0 E:\xampp\htdocs\vendor\guzzlehttp\guzzle\src\Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 E:\xampp\htdocs\vendor\guzzlehttp\promises\src\Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 E:\xampp\htdocs\vendor\guzzlehttp\promises\src\Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 E:\xampp\htdocs\vendor\guzzlehttp\promises\src\TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 E:\xampp\htdocs\vendor\guzzlehttp\promises\sr in E:\xampp\htdocs\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://graph.microsoft.com/v1.0/me/messages` resulted in a `403 Forbidden` response:
{"error":{"code":"ErrorAccessDenied","message":"Access is denied. Check credentials and try again."}}
 in E:\xampp\htdocs\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
Stack trace:
#0 E:\xampp\htdocs\vendor\guzzlehttp\guzzle\src\Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 E:\xampp\htdocs\vendor\guzzlehttp\promises\src\Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 E:\xampp\htdocs\vendor\guzzlehttp\promises\src\Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 E:\xampp\htdocs\vendor\guzzlehttp\promises\src\TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 E:\xampp\htdocs\vendor\guzzlehttp\promises\sr in E:\xampp\htdocs\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

The script that I'm using:

$client = new \Microsoft\Graph\Graph();

$clientId = 'xxx-xxx-xxx';
$tenantId = 'xxx-xxx-xxx';
$clientSecret = 'xxx-xxx-xxx';
$username = 'user@sonova.com';
$pwd = 'password';

$scopes = [
    'user.read', 
	'openid', 
	'profile', 
	'offline_access', 
	'IMAP.AccessAsUser.All',
];

$tokenUri = 'https://login.microsoftonline.com/'.$tenantId.'/oauth2/v2.0/token';

$postFields = 'client_id=' . $clientId
			. '&scope=' . urlencode(implode(' ', $scopes))
			. '&client_secret=' . urlencode($clientSecret)
			. '&username=' . $username 
			. '&password=' . $pwd
			. '&grant_type=password';

$curl = curl_init();
curl_setopt($curl, CURLOPT_URL, $tokenUri);
curl_setopt($curl, CURLOPT_POST, TRUE);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($curl, CURLOPT_POSTFIELDS, $postFields);
$tmp = json_decode(curl_exec($curl), true);

$client->setAccessToken($tmp['access_token']);
$user = $client->createRequest("GET", "/me/")
              ->setReturnType(\Microsoft\Graph\Model\User::class)
              ->execute();
var_dump($user);

$client->setAccessToken($tmp['access_token']);
$messages = $client->createRequest("GET", "/me/messages")
              ->setReturnType(\Microsoft\Graph\Model\Message::class)
              ->execute();
var_dump($messages);

The first request (/me) is working, and I receive the needed information (login and access_token is working), but when I call the /me/messages I receive the 403 error.

here are the App permissions:
![image](https://user-images.githubusercontent.com/16977689/208178955-a1b7d81e-9551-4a98-a725-f6ac598c1d9b.png)

Any idea? It is really urgent because currently, we are using the basic auth to get the emails, and this way won't be available after the end of this year.

We also have to use the 'silent' authentication because a PHP script will read and process the inbound messages.

Thanks for the help!

**Comment by JooRichard** [comment]
If I add the Mail.Read scope to the access token request I got the following error:
"error_description": AADSTS65001: The user or administrator has not consented to use the application with ID 'xxx-xxx-xxx' named 'app_name'. Send an interactive authorization request for this user and resource.

**Comment by JooRichard** [comment]
.
