### ISSUE TITLE
[Snippet generation] No snippet generated for /communications/calls/logTeleconferenceDeviceQuality

### ISSUE THREAD

**Issue by isvargasmsft** [microsoftgraph/msgraph-sdk-php#1302]
This is only affecting PHP.

Original HTTP Snippet:
```http
POST /v1.0/communications/calls/logTeleconferenceDeviceQuality HTTP/1.1
Content-type: application/json
Host: graph.microsoft.com
Content-Length: 3505


{
"quality": {
"@odata.type": "#microsoft.graph.teleconferenceDeviceQuality",
"callChainId": "0622673d-9f69-49b3-9d4f-5ec64f42ecce",
"participantId": "ea078406-b5d4-4d3c-b85e-90103dcec7f6",
"mediaLegId": "bd9ee398-4b9d-42c7-8b8d-4e8efad9435f",
"deviceName": "TestAgent",
"deviceDescription": "TestDescription",
"mediaQualityList": [
{
"@odata.type": "#microsoft.graph.teleconferenceDeviceAudioQuality",
"channelIndex": 1,
"mediaDuration": "PT20M",
"networkLinkSpeedInBytes": 13000,
"localIPAddress": "127.0.0.1",
"localPort": 6300,
"remoteIPAddress": "102.1.1.101",
"remotePort": 6301,
"inboundPackets": 5500,
"outboundPackets": 5400,
"averageInboundPacketLossRateInPercentage": 0.01,
"averageOutboundPacketLossRateInPercentage": 0.02,
"maximumInboundPacketLossRateInPercentage": 0.05,
"maximumOutboundPacketLossRateInPercentage": 0.06,
"averageInboundRoundTripDelay": "PT0.03S",
"averageOutboundRoundTripDelay": "PT0.04S",
"maximumInboundRoundTripDelay": "PT0.13S",
"maximumOutboundRoundTripDelay": "PT0.14S",
"averageInboundJitter": "PT0.01S",
"averageOutboundJitter": "PT0.015S",
"maximumInboundJitter": "PT0.023S",
"maximumOutboundJitter": "PT0.024S"
},
{
"@odata.type": "#microsoft.graph.teleconferenceDeviceVideoQuality",
"channelIndex": 1,
"mediaDuration": "PT20M",
"networkLinkSpeedInBytes": 13000,
"localIPAddress": "127.0.0.1",
"localPort": 6300,
"remoteIPAddress": "102.1.1.101",
"remotePort": 6301,
"inboundPackets": 5500,
"outboundPackets": 5400,
"averageInboundPacketLossRateInPercentage": 0.01,
"averageOutboundPacketLossRateInPercentage": 0.02,
"maximumInboundPacketLossRateInPercentage": 0.05,
"maximumOutboundPacketLossRateInPercentage": 0.06,
"averageInboundRoundTripDelay": "PT0.03S",
"averageOutboundRoundTripDelay": "PT0.04S",
"maximumInboundRoundTripDelay": "PT0.13S",
"maximumOutboundRoundTripDelay": "PT0.14S",
"averageInboundJitter": "PT0.01S",
"averageOutboundJitter": "PT0.015S",
"maximumInboundJitter": "PT0.023S",
"maximumOutboundJitter": "PT0.024S"
},
{
"@odata.type": "#microsoft.graph.teleconferenceDeviceScreenSharingQuality",
"channelIndex": 1,
"mediaDuration": "PT20M",
"networkLinkSpeedInBytes": 13000,
"localIPAddress": "127.0.0.1",
"localPort": 6300,
"remoteIPAddress": "102.1.1.101",
"remotePort": 6301,
"inboundPackets": 5500,
"outboundPackets": 5400,
"averageInboundPacketLossRateInPercentage": 0.01,
"averageOutboundPacketLossRateInPercentage": 0.02,
"maximumInboundPacketLossRateInPercentage": 0.05,
"maximumOutboundPacketLossRateInPercentage": 0.06,
"averageInboundRoundTripDelay": "PT0.03S",
"averageOutboundRoundTripDelay": "PT0.04S",
"maximumInboundRoundTripDelay": "PT0.13S",
"maximumOutboundRoundTripDelay": "PT0.14S",
"averageInboundJitter": "PT0.01S",
"averageOutboundJitter": "PT0.015S",
"maximumInboundJitter": "PT0.023S",
"maximumOutboundJitter": "PT0.024S"
}
]
}
}
```

Error message:
Exception while processing /home/vsts/work/1/a/Snippets/call-logteleconferencedevicequality-v1-httpSnippet.
Unsupported PropertyType: Guid
at CodeSnippetsReflection.OpenAPI.LanguageGenerators.PhpGenerator.WriteCodeProperty(String propertyAssignment, StringBuilder payloadSb, CodeProperty parent, CodeProperty child, IndentManager indentManager, Int32 childPosition, String childPropertyName, Boolean f

Stack trace: 
at CodeSnippetsPipeline.Test.CodeSnippetsPipeline.Test(String httpSnippetFilePath, String language) in /home/vsts/work/1/s/CodeSnippetsPipeline.Test/CodeSnippetsPipeline.cs:line 56
   at InvokeStub_CodeSnippetsPipeline.Test(Object, Object, IntPtr*)

1)    at CodeSnippetsPipeline.Test.CodeSnippetsPipeline.Test(String httpSnippetFilePath, String language) in /home/vsts/work/1/s/CodeSnippetsPipeline.Test/CodeSnippetsPipeline.cs:line 56
   at InvokeStub_CodeSnippetsPipeline.Test(Object, Object, IntPtr*)

**Comment by isvargasmsft** [comment]
CC: @SilasKenneth @Ndiritu

**Comment by SilasKenneth** [comment]
Fixed in https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1680
