### ISSUE TITLE
Get email attachment that is itself an email

### ISSUE THREAD

**Issue by JacoSJKruger** [microsoftgraph/msgraph-sdk-php#1428]
In the new version when an email has an attachment, but that attachment is itself an email, then this is handled as an 'Item'.

It does not have the standard properties like ContentBytes and ContentId.
I would however like to download this file/item programatically but things like $emailAttachment->getContentBytes(); do not work.

I've also tried getting creative like:

$fileContents = $graphServiceClient->users()->byUserId($user_id)->messages()->byMessageId($email->getId())->attachments()->byAttachmentId($emailAttachment->getId())->content()->get()->wait();

But alas, still not working.
Any ideas?

**Comment by inserve-paul** [comment]
Hi @JacoSJKruger,

I've also encountered this issue, and found a workaround for this.
First of all I build the request as usual. In stead of calling the ->get() parameter, I obtain the requestInformation.
After that I change the urlTemplate by adding the /$value parameter, and use that object in the sendPrimitiveAsync() method and let it return a string, to get the actual content of the attachment.

Not ideal, but I didn't find any other way in the current SDK to get the actual content.

```php
$getRequest = $graphServiceClient
    ->users()
    ->byUserId($userId)
    ->messages()
    ->byMessageId($messageId)
    ->attachments()
    ->byAttachmentId($attachmentId)
    ->toGetRequestInformation();

// Change the urlTemplate to add the $value parameter
$getRequest->urlTemplate .= '/%24value';

$attachmentContent = $graphServiceClient
    ->getRequestAdapter()
    ->sendPrimitiveAsync($getRequest, 'string')
    ->wait();
```

**Comment by VilainMamuth** [comment]
Thx @inserve-paul  but got this error :(

Fatal error: Uncaught UnexpectedValueException: Content type application/gzip does not have a factory to be parsed in /var/www/html/m365/vendor/microsoft/kiota-abstractions/src/Serialization/ParseNodeFactoryRegistry.php:52 
Stack trace: 
#0 /var/www/html/m365/vendor/microsoft/kiota-http-guzzle/src/GuzzleRequestAdapter.php(504): Microsoft\Kiota\Abstractions\Serialization\ParseNodeFactoryRegistry->getRootParseNode() 
#1 /var/www/html/m365/vendor/microsoft/kiota-http-guzzle/src/GuzzleRequestAdapter.php(281): Microsoft\Kiota\Http\GuzzleRequestAdapter->getRootParseNode() #2 /var/www/html/m365/vendor/php-http/promise/src/FulfilledPromise.php(39): Microsoft\Kiota\Http\GuzzleRequestAdapter->Microsoft\Kiota\Http\{closure}() 
#3 /var/www/html/m365/vendor/microsoft/kiota-http-guzzle/src/GuzzleRequestAdapter.php(311): Http\Promise\FulfilledPromise->then() 
#4 /var/www/html/m365/GraphHelper.php(152): Microsoft\Kiota\Http\GuzzleRequestAdapter->sendPrimitiveAsync() 
#5 /var/www/html/m365/fetcher.php(29): GraphHelper->getAttachment() 
#6 {main} 
thrown in /var/www/html/m365/vendor/microsoft/kiota-abstractions/src/Serialization/ParseNodeFactoryRegistry.php on line 52
