### ISSUE TITLE
Migrating from 1.96 to 2.4 booking service issue

### ISSUE THREAD

**Issue by shirofuji** [microsoftgraph/msgraph-sdk-php#1504]
Updating from 2.4 I'm trying to get the booking service using the following basic code:

```
$services = $client->solutions()->bookingBusinesses()->byBookingBusinessId($businessId)->services()->get()->wait();
```
The request seem to work but the parsing in the model seem to produce an issue:
```
Uncaught Exception: Unknown or bad format (-PT15M) in C:\xampp74\htdocs\wp\wordpress\wp-content\plugins\CustomPlugin\vendor\microsoft\kiota-serialization-json\src\JsonParseNode.php:285 Stack trace: #0 C:\xampp74\htdocs\wp\wordpress\wp-content\plugins\CustomPlugin\vendor\microsoft\kiota-serialization-json\src\JsonParseNode.php(285): DateInterval->__construct('-PT15M') #1 C:\xampp74\htdocs\wp\wordpress\wp-content\plugins\CustomPlugin\vendor\microsoft\microsoft-graph\src\Generated\Models\BookingReminder.php(71): Microsoft\Kiota\Serialization\Json\JsonParseNode->getDateIntervalValue()
```

**Comment by SilasKenneth** [comment]
Hi @shirofuji , Thank you for trying the SDK. I am very sorry for the issue you are facing. I am able to reproduce and will be issuing a fix as soon as possible.
