### ISSUE TITLE
Getting "Invalid enum value unknown" when not settings userPurpose

### ISSUE THREAD

**Issue by antoniom** [microsoftgraph/msgraph-sdk-php#1565]
### Describe the bug

I am trying to update the `mailboxSettings` of a user via the following script

````php
$mailboxSettings = new MailboxSettings();

$automaticRepliesSetting = new AutomaticRepliesSetting();
$automaticRepliesSetting->setStatus(new AutomaticRepliesStatus(AutomaticRepliesStatus::DISABLED));
$automaticRepliesSetting->setExternalAudience(new ExternalAudienceScope(ExternalAudienceScope::ALL));
$automaticRepliesSetting->setExternalReplyMessage("I am out of office with limited access to email.");
$automaticRepliesSetting->setInternalReplyMessage("I am out of office with limited access to email.");
$mailboxSettings->setAutomaticRepliesSetting($automaticRepliesSetting);

$response = $msGraph
    ->getClient()
    ->users()
    ->byUserId(<USERID>)
    ->mailboxSettings()
    ->patch($mailboxSettings)
    ->wait();
```

And i receive the following exception
```
Exception 'InvalidArgumentException' with message 'Invalid enum value unknown'

in /var/www/html/vendor/microsoft/kiota-abstractions/src/Enum.php:57

Stack trace:
#0 /var/www/html/vendor/microsoft/kiota-serialization-json/src/JsonParseNode.php(164): Microsoft\Kiota\Abstractions\Enum->__construct('unknown')
#1 /var/www/html/vendor/microsoft/microsoft-graph/src/Generated/Models/MailboxSettings.php(121): Microsoft\Kiota\Serialization\Json\JsonParseNode->getEnumValue('Microsoft\\Graph...')
#2 /var/www/html/vendor/microsoft/kiota-serialization-json/src/JsonParseNode.php(141): Microsoft\Graph\Generated\Models\MailboxSettings->Microsoft\Graph\Generated\Models\{closure}(Object(Microsoft\Kiota\Serialization\Json\JsonParseNode))
#3 /var/www/html/vendor/microsoft/kiota-serialization-json/src/JsonParseNode.php(114): Microsoft\Kiota\Serialization\Json\JsonParseNode->assignFieldValues(Object(Microsoft\Graph\Generated\Models\MailboxSettings))
#4 /var/www/html/vendor/microsoft/kiota-http-guzzle/src/GuzzleRequestAdapter.php(170): Microsoft\Kiota\Serialization\Json\JsonParseNode->getObjectValue(Array)
#5 /var/www/html/vendor/php-http/promise/src/FulfilledPromise.php(39): Microsoft\Kiota\Http\GuzzleRequestAdapter->Microsoft\Kiota\Http\{closure}(Object(GuzzleHttp\Psr7\Response))
#6 /var/www/html/vendor/microsoft/kiota-http-guzzle/src/GuzzleRequestAdapter.php(145): Http\Promise\FulfilledPromise->then(Object(Closure))
#7 /var/www/html/vendor/microsoft/microsoft-graph/src/Generated/Users/Item/MailboxSettings/MailboxSettingsRequestBuilder.php(59): Microsoft\Kiota\Http\GuzzleRequestAdapter->sendAsync(Object(Microsoft\Kiota\Abstractions\RequestInformation), Array, Array)
#8 /var/www/html/commands/OutOfOfficeController.php(99): Microsoft\Graph\Generated\Users\Item\MailboxSettings\MailboxSettingsRequestBuilder->patch(Object(Microsoft\Graph\Generated\Models\MailboxSettings))
```
MailboxSettings.php(121) -> points to UserPurpose which is a readonly value and shouldn't be set.

If a try to set it
e.g.
```php
$mailboxSettings->setUserPurpose(new UserPurpose(UserPurpose::ROOM));
```
I get
The property 'userPurpose' was specified but is not supported with this request.

### Expected behavior

The request to succeed without request to set userPurpose property

### How to reproduce

Execute the above script

### SDK Version

2.12.0

### Latest version known to work for scenario above?

_No response_

### Known Workarounds

_No response_

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>


### Configuration

PHP 8.3

### Other information

_No response_

**Comment by timayabi2020** [comment]
@antoniom, thank you for raising this issue.  After investigations, I found out that the service is returning an undefined/undocumented value (``unkown``) for the property ``userPurpose``. 
<img width="639" alt="image" src="https://github.com/user-attachments/assets/70efa346-2778-4cbe-83e2-a092dfddfe05">
Based on the documentation here https://learn.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0#userpurpose-values, the value ``unkown`` is not among the list of documented enums.
<img width="442" alt="image" src="https://github.com/user-attachments/assets/5920c269-af6d-4ced-8f64-0cdf464687b9">
It is also not specified in the OpenAPI file used to generate this particular service in the SDK.
<img width="178" alt="image" src="https://github.com/user-attachments/assets/ce5f42c7-648c-4445-bd6d-677593ae20fa">

Unfortunately for API related issues/questions we are not best placed to give an answer. Kindly raise an issue here https://developer.microsoft.com/en-us/graph/support so that the API owner can respond to it.
